services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
     - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080

  etl_runner: 
    image: etl_runner
    container_name: etl_runner
    build:
      context: ./
      dockerfile: ./containers/pipelinerunner/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}


